### PR TITLE
Telegram Spoiler & Image Albums

### PR DESCRIPTION
**Pull request by IsoFrieze**
+ Posts with more than one image will group into an album instead of being separate posts (max 10 per post)
+ Posts can be spoilered (requires edits to MTProto as it is out of date)

MTProto hasn't been updated since Telegram released spoilers to image and document attachements.
The following changes need to be made to `node_modules/@mtproto/core/src/tl/builder/index.js` to support spoilers.
Each `const flags` variable needs the following appended to it:

L347: `inputMediaUploadedPhoto` - `(this.has(params.spoiler) << 2)`
L355: `inputMediaPhoto` - `(this.has(params.spoiler) << 1)`
L1330: `inputMediaUploadedDocument` - `(this.has(params.spoiler) << 5)`
L1341: `inputMediaDocument` - `(this.has(params.spoiler) << 2)`
L2703: `inputMediaPhotoExternal` - `(this.has(params.spoiler) << 1)`
L2710: `inputMediaDocumentExternal` - `(this.has(params.spoiler) << 1)`

### CODE REVIEW

**Comment by mvdicarlo** [comment]
So in order for this to work, it will require injecting code into the mtproto package manually each time?

**Comment by askmeaboutlo0m** [comment]
For my purposes, I went and vendored the thing. Just pulled it into a directory and then pointed the package.json at that. I think this should show a diff, it's split into a few commits and it fixes the storage stuff that I think is currently busted: <https://github.com/mvdicarlo/postybirb-plus/compare/develop...askmeaboutlo0m:postybirb-plus:telegram-spoilers?expand=1>

**Comment by mvdicarlo** [comment]
Not forgotten. I will look at vendoring locally as well to support these changes.

**Comment by leaftail1880** [comment]
im currently working on it

**Comment by leaftail1880** [comment]
im found that too late, im working on it too, but also adding support for long descriptions and better message send order

Also, i fast checked mtproto/core 6.3.0 and found that it has support for spoilers (in electron-app package.json there is 6.2.0 version)

@IsoFrieze @mvdicarlo should i wait untill this pr is merged to open mine?

**Comment by IsoFrieze** [comment]
If it's as simple as just updating to the latest version of mtproto then I'd wait on that yeah

**Comment by mvdicarlo** [comment]
@IsoFrieze Could you remove the package-lock file to clean the conflicts?
Will get this merged as soon as conflicts are gone.

I'll update the mtproto lib once this is in.

**Comment by IsoFrieze** [comment]
Should be good to go I think.

**Comment by mvdicarlo** [comment]
Thanks for your contribution. I'll update mtproto in latest.

**Pull request merged**
