### PR TITLE
fix: add aspect ratio to bsky embed

### PR DESCRIPTION
**Pull request by leaftail1880**
изображение

### CODE REVIEW

**Comment by leaftail1880** [comment]
Related to https://github.com/bluesky-social/social-app/issues/6800

**Comment by askmeaboutlo0m** [comment]
Tried this out, works.

**Comment by mistydemeo** [comment]
Tested and this works for me too! Thank you.

Sample posts (bottom one made before this patch, top one made after):

Screenshot 2024-12-07 at 10-53-45 CD-i (@cd-i bsky social) — Bluesky

**Comment by mvdicarlo** [comment]
I will merge an release this when I get time. Probably Sunday. Apologies for the wait.

**Pull request merged**
