### PR TITLE
Tag shortcut expansion

### PR DESCRIPTION
**Pull request by aneillans**
This resolves a couple of issues around using the {tags} shortcut in descriptions for services such as Mastodon, Pleroma, Bluesky etc

The {tags} shortcut was not going through the convertors, so was not parsing properly, it also was not parsing out spaces correctly (i.e. website specific adaptions).

Also added an option to the sites that we are currently appending the tags automatically onto descriptions on to allow turning this off for people that might be using the {tags} shortcut to avoid duplication.

### CODE REVIEW

**Comment by mvdicarlo** [comment]
So overall I am not really fine about this change and am likely to reject it.
My typical philosophy is that if a user wanted tags in their description they should add it in manually. Annoying? Yes. But supporting auto-injection is unwieldy and likely to have unintended affects for a user's post.

I was already hesitant about tag injection within mastodon and the such and this is kind of re-affirming my bias.
I am more tempted to just remove the hashtag injection as it exists now, add the parsing section into the description parser for {tags} and call it there.

**Comment by aneillans** [comment]
Don't see an issue with that approach; removing the auto injection of tags wouldn't be an issue if {tags} parsing was corrected (as per this PR or another implementation).

**Comment by mvdicarlo** [comment]
Will look into that if you don't after I figure out the furrynetwork nightmare.

Overall the change will be to remove tag injection that happens in any posting logic (mastodon, etc.). Ensure that all implementations aren't doing any weird tag modification outside of their parseTags functions, and then making the description parser able to correctly inject.

**Comment by aneillans** [comment]
Yeah - I should get time to take a look this week - will let you know :)

**Comment by aneillans** [comment]
Closing this, as superseded by 286.

**Pull request closed without merging**
