### PR TITLE
Fix Ko-Fi post status parsing, Furry-Network error inspection

### PR DESCRIPTION
**Pull request by leaftail1880**
For some reason Ko-Fi post.body can be \u0000\u0007\u0000{"success":true}\u0003
Report: https://discord.com/channels/395931304870281216/580751000835588156/1216467099975942334

Fixes BrowserWindowUtil.runScriptOnPage error handling to be more informative instead of just `Script failed to execute`
Report: https://discord.com/channels/395931304870281216/580751000835588156/1217943590718799962

### CODE REVIEW

**Comment by mvdicarlo** [comment]
will get this in this upcoming week, apologies for the wait

**Comment by mvdicarlo** [comment]
have these all been manually tested to not break any returns?

**Comment by leaftail1880** [comment]
I dont have accounts on these websites (ko-fi, furry-network, patreon, subscribestar(adult)) so im not sure how should i test these. Maybe i should make local build and send it to people who have those websites setup

**Comment by mvdicarlo** [comment]
Usually the answer would be to create an account to test with.

**Comment by mvdicarlo** [comment]
My largest gripe modifying many websites all at once. Can this be backed down to just kofi and FN?

**Review by mvdicarlo — COMMENTED** [review]
So did a quick test. I guess we have to be careful now to ensure the there is a return keyword in all of these calls

**Comment by leaftail1880** [comment]
Ive searched all across the code and ensured that every runScriptOnPage has return keyword. Hovewer, im not sure about some site that has PHP.get()

Does runScriptOnPage supports php or is that PHP/JS bridge?

**Pull request merged**
